version = 1

exclude_patterns = [
  "src/CONSTANTS.py",
  "sample_config.yml",
  "src/CONSTANTS.py",
  "src/utils/update.py",
  "**/__init__.py"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"

[[transformers]]
name = "ruff"