version = 1

exclude_patterns = [
"src/CONSTANTS.py",
"src/DEFAULT_USER_INPUT.py"
]

[[analyzers]]
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"

[[transformers]]
name = "autopep8"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"
