version = 1

exclude_patterns = [
  "sample_config.yml",
  "src/utils/update.py"
]

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["Dockerfile"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"