ci:
  autoupdate_schedule: weekly
  autofix_commit_msg: "🐛 [pre-commit.ci]: Auto Fix"
  autofix_prs: true
  autoupdate_commit_msg: "🔧 [pre-commit.ci]: pre-commit autoupdate"

exclude: ^(src/utils/update.py)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: pretty-format-json

  # - repo: https://github.com/asottile/setup-cfg-fmt
  #   rev: v2.5.0
  #   hooks:
  #     - id: setup-cfg-fmt

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
        args: [--py39-plus, --add-import, "from __future__ import annotations"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa

  # - repo: https://github.com/pylint-dev/pylint
  #   rev: v3.1.0
  #   hooks:
  #     - id: pylint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
