ci:
  autoupdate_schedule: weekly
  autofix_commit_msg: "🐛 fix: pre-commit auto fix"
  autofix_prs: true
  autoupdate_commit_msg: "🔧 chore (deps): pre-commit auto update dependencies"

exclude: ^(src/utils/update.py)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
      - id: trailing-whitespace
        exclude: "^(docs/README.md|src/constants.py|assets/utils/ascii_banner.txt)"
      - id: end-of-file-fixer
        exclude: "^(docs/README.md)"
      - id: debug-statements
      # - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      # - id: pretty-format-json

  # - repo: https://github.com/asottile/setup-cfg-fmt
  #   rev: v2.5.0
  #   hooks:
  #     - id: setup-cfg-fmt

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        types: [python]
        args: ["--rcfile=.pylintrc", "--disable=F0401"]

  # - repo: https://github.com/sourcery-ai/sourcery
  #   rev: v1.15.0
  #   hooks:
  #     - id: sourcery
  #       # The best way to use Sourcery in a pre-commit hook:
  #       # * review only changed lines:
  #       # * omit the summary
  #       args: [--diff=git diff HEAD, --no-summary]

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
      - id: ruff-format

  # - repo: https://github.com/PyCQA/isort
  #   rev: "5.13.2"
  #   hooks:
  #     - id: isort

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: "config-sample.yml"

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.3"
    hooks:
      - id: editorconfig-checker
        exclude: "^(docs/README.md)"
