name: 🐞 Bug report
description: You are facing issue? 😐
title: "🐛 "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please keep the emoji "🐛" in the title.
        You can use either Vietnamese or English.
  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug description
      placeholder: What bug are you facing 🥱
    validations:
      required: true
  - type: checkboxes
    id: os
    attributes:
      label: 💻 OS
      description: |
        Choose your OS you are using
      options:
        - label: Windows
        - label: macOS
        - label: Linux / Other
  - type: textarea
    id: other-os
    attributes:
      label: 🖥️ Linux distro / Other
      description: |
        Linux: Which distro are you using?
        Other: Please fill it in here.
      placeholder: "Ví dụ: Ubuntu, Arch, Manjaro, ..."
    validations:
      required: false
  - type: textarea
    id: python-version
    attributes:
      label: 💁‍♂️ Python version
      description: Python version if you use it as python
    validations:
      required: false
  - type: textarea
    id: note
    attributes:
      label: 📝 Note
      description: Do you have any notes?
    validations:
      required: false
