name: 💫 Feature request
description: Request new feature
title: "✨ "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please keep the emoji "✨" in the title.
        You can use either Vietnamese or English.
        Please request 1 feature per issue.
  - type: textarea
    id: feature-description
    attributes:
      label: 📈 Feature description
      placeholder: Describe the feature
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: 📝 Note
      placeholder: Do you have any notes?
    validations:
      required: false
