name: ❓ Question
description: You have (a) question(s)?
title: "❓ "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Please keep the emoji "❓" in the title.
        You can use either Vietnamese or English.
  - type: textarea
    id: question-description
    attributes:
      label: 🤔 Question(s)
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: 📝 Note
      description: Do you have any notes?
    validations:
      required: false
