name: 🙏 Update request
description: Update request when VNULIB changes their schemes.
title: "🔨 VNULIB schemes update request"
labels: ["vnulib update"]
body:
  - type: markdown
    attributes:
      value: |
        Please keep the title as it is.
        You can use either Vietnamese or English.
  - type: textarea
    id: update-description
    attributes:
      label: 🔨 Describe the update
      placeholder: |
        Could you describe more about the changed scheme(s)?
    validations:
      required: false
  - type: dropdown
    id: still-working
    attributes:
      label: 🤥 Still working?
      description: |
        Does the latest version of the tool still working properly?
      options:
        - "Yes"
        - "Nope"
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: 📝 Note
      description: Do you have any notes?
    validations:
      required: false
