version: 1
disable_existing_loggers: False
formatters:
  simple:
    "format": "%(levelname)s\t: %(message)s"
  verbose:
    "format": "%(asctime)s - %(levelname)s - %(message)s - %(filename)s:%(lineno)d"
handlers:
  stdout:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: simple
    level: INFO
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: verbose
    filename: "VNULIB-DOWNLOADER/logs/tool.log"
    maxBytes: 20000 # 2KB
    backupCount: 3
    level: DEBUG
    encoding: utf-8
loggers:
  vnulib_downloader:
    level: DEBUG
    handlers:
      - file
root:
  level: DEBUG
  handlers:
    - stdout