version: 1
disable_existing_loggers: true
formatters:
  simple:
    "format": "[%(levelname)s]: %(message)s"
  verbose:
    "format": "%(asctime)s [%(levelname)-8s] - %(message)s (%(filename)s:%(lineno)d)"
  detail:
    "format": "%(asctime)s [%(levelname)-8s] - %(message)s (%(pathname)s:%(lineno)d)"
handlers:
  stdout:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: simple
    level: INFO
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: verbose
    filename: "log/tool.log"
    maxBytes: 200 # 20000 # 2KB
    backupCount: 3
    level: DEBUG
    encoding: utf-8
loggers:
  vnulib_downloader:
    level: DEBUG
    handlers:
      - stdout
      - file
    propogate: false
root:
  level: CRITICAL
  propogate: false
