version: 1
disable_existing_loggers: true
formatters:
  simple:
    "format": "[%(levelname)s]: %(message)s"
  verbose:
    "format": "%(asctime)s [%(levelname)-8s] - %(message)s (%(filename)s:%(lineno)d)"
  detail:
    "format": "%(asctime)s [%(levelname)-8s] - %(message)s (%(pathname)s:%(lineno)d)"
handlers:
  stdout_handler:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: simple
    level: INFO
  file_handler:
    class: logging.FileHandler
    formatter: verbose
    filename: "log/tool.log"
    level: DEBUG
    encoding: utf-8
  rotating_file_handler: # Problem of RotatingFileHandler: https://python-forum.io/thread-19104.html
    class: logging.handlers.RotatingFileHandler
    formatter: verbose
    filename: "log/tool.log"
    maxBytes: 50000 # 5KB
    backupCount: 3
    level: DEBUG
    encoding: utf-8
    delay: false
loggers:
  vnulib_downloader:
    level: DEBUG
    handlers:
      - stdout_handler
      - rotating_file_handler
    propogate: false
  vnulib_downloader_queue_listener:
    level: DEBUG
    handlers:
      - stdout_handler
      - file_handler
    propogate: false
  vnulib_downloader_sub_process:
    level: DEBUG
    propogate: false
