version: 1
disable_existing_loggers: true
formatters:
  simple:
    "format": "[%(levelname)s]: %(message)s"
  verbose:
    "format": "%(asctime)s [%(levelname)-8s] - %(message)s (%(filename)s:%(lineno)d)"
  detail:
    "format": "%(asctime)s [%(levelname)-8s] - %(message)s (%(pathname)s:%(lineno)d)"
handlers:
  stdout:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: simple
    level: INFO
  rotating_file:
    class: logging.handlers.RotatingFileHandler
    formatter: verbose
    filename: "log/tool.log"
    maxBytes: 500 # 20000 # 2KB
    backupCount: 3
    level: DEBUG
    encoding: utf-8
    mode: a
  queue_handler:
    class: logging.handlers.QueueHandler
    handlers:
      - stdout
      - rotating_file
    respect_handler_level: true
loggers:
  vnulib_downloader:
    level: DEBUG
    handlers:
      - stdout
      - rotating_file
    propogate: false
  vnulib_downloader_queue:
    level: DEBUG
    handlers:
      - queue_handler
    propogate: false
# root:
#   handlers:
#     - stdout
#     - rotating_file
#   level: DEBUG
#   propogate: false
