name: Code Check

concurrency:
  cancel-in-progress: true
  group: code-check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  code-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@main

      - name: Install python
        uses: actions/setup-python@main
        with:
          cache: pip
          python-version: "3.12"

      - name: Install Sourcery
        run: pip install sourcery

      - name: Install Pre-commit
        run: pip install pre-commit

      - name: Run Sourcery
        if: ${{ always() }}
        run: sourcery login --token "${{ secrets.SOURCERY_TOKEN }}" && sourcery review .

      - name: Run Pre-commit
        if: ${{ always() }}
        run: pre-commit run --all-files

      - name: Update pre-commit hook
        if: ${{ always() }}
        run: pre-commit autoupdate

      - uses: stefanzweifel/git-auto-commit-action@master
        if: ${{ always() }}
        with:
          commit_message: "🎨 refactor: auto code check"
