name: Code Check

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  code-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@main

      - name: Install python
        uses: actions/setup-python@main
        with:
          cache: pip
          python-version: "3.12"

      - name: Install Sourcery
        run: pip install sourcery

      - name: Install Pre-commit
        run: pip install pre-commit

      - name: Run Sourcery
        if: ${{ always() }}
        run: sourcery login --token "${{ secrets.SOURCERY_TOKEN }}" && sourcery review .

      - name: Run Pre-commit
        if: ${{ always() }}
        run: pre-commit run --all-files

      # - name: Update pre-commit hook
      #   if: ${{ always() }}
      #   run: pre-commit autoupdate

      # - uses: stefanzweifel/git-auto-commit-action@master
      #   if: ${{ always() }}
      #   with:
      #     commit_message: "🎨 refactor: auto code check"
      #     branch: bot/auto_code_check

      - name: Create Pull Request
        if: ${{ always() }}
        uses: peter-evans/create-pull-request@v7
        with:
          reviewers: KevinNitroG
          title: "🎨 refactor: auto code check"
          delete-branch: true
          commit-message: "🎨 refactor: auto code check"
          branch-suffix: short-commit-hash
          labels: enhancement
          branch: bot/code-check
