name: Release

on:
  push:
    paths:
      - src/constants.py
  workflow_dispatch:

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      VERSION: ${{ steps.get_variables.outputs.VERSION }}
      SET_PRE_RELEASE: ${{ steps.get_variables.outputs.SET_PRE_RELEASE }}
      CONTINUE: ${{ steps.get_variables.outputs.CONTINUE }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Prepare Version & Set Pre Release
        id: get_variables
        run: script/checkRelease.sh

  build:
    name: build
    needs: prepare
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    if: ${{ needs.prepare.outputs.CONTINUE == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Install python
        uses: actions/setup-python@main
        with:
          cache: pip
          python-version: "3.12"

      - name: Install dependacies
        run: pip install -r requirements.txt && pip install pyinstaller

      - name: Build for ${{ matrix.os }}
        run: pyinstaller --noconfirm --onefile --console --icon "asset/image/VNU_HCM_LOGO-256.ico" --name "VNULIB-Downloader-${{ matrix.os }}" --log-level "INFO" --add-data "src/:src/" --add-data "LICENSE:." "main.py"

      - name: Upload to artifact
        uses: actions/upload-artifact@main
        with:
          name: VNULIB-Downloader-${{ matrix.os }}
          path: dist/VNULIB-Downloader-*
          compression-level: 6
          retention-days: 30

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - prepare
      - build
    if: ${{ needs.prepare.outputs.CONTINUE == 'true' }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@main

      - name: Upload to Release
        uses: svenstaro/upload-release-action@master
        with:
          body: ${{ needs.prepare.outputs.VERSION }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./VNULIB-Downloader-*/VNULIB-Downloader-*
          release_name: VNULIB Downloader ${{ needs.prepare.outputs.VERSION }}
          tag: ${{ needs.prepare.outputs.VERSION }}
          file_glob: true
          overwrite: false
          prerelease: ${{ needs.prepare.outputs.SET_PRE_RELEASE }}
